version: '3.8'

services:
  head-server:
    build:
      context: .
      dockerfile: Dockerfile.head
      tags: ["iobt25-head-server:latest"]
    container_name: iobt25-head-server
    ports:
      - "8185:8185"
    volumes:
      # Mount your Python source code for development (comment out for production)
      - ./system:/app/system
      # Mount your ONNX models directory
      - ./models:/app/models:ro
      # Mount logs directory (optional)
      - ./logs:/app/logs
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Jetson-specific runtime requirements
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Override default command if needed
    entrypoint: ["python3", "system/head_server.py"]
    command: ["-m", "ensemble-effnet-c5-lr-0.005-tin", "-p", "8185"]