services:
  s2-server:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: iobt26-server:latest
    container_name: iobt26-s2-server
    volumes:
      - ./system:/app/system
      - ./models:/app/models:ro
      - ./logs:/app/logs
      - ./3rdparty:/app/3rdparty
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    restart: "no"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["python3", "system/single_server.py"]
    command: ["-m", "${MODEL:-ensemble-effnet-c5-lr-0.005-tin}", "-n", "2", "-p", "${PORT:-8182}", "-s", "${HEAD:-192.168.79.12:8180}"]
    network_mode: "host"
