services:
  head-server:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: iobt26-server:latest
    container_name: iobt26-head-server
    volumes:
      - ./system:/app/system
      - ./models:/app/models:ro
      - ./logs:/app/logs
      - ./3rdparty:/app/3rdparty
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    restart: "no"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["python3", "system/head_server.py"]
    command: ["-m", "${FAIL_MODEL:-ensemble-effnet-c5-lr-0.005-tin}", "-p", "8180"]
    network_mode: "host"

  s1-server:
    image: iobt26-server:latest
    container_name: iobt26-s1-server
    volumes:
      - ./system:/app/system
      - ./models:/app/models:ro
      - ./logs:/app/logs
      - ./3rdparty:/app/3rdparty
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    restart: "no"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["python3", "system/single_server.py"]
    command: ["-m", "${FAIL_MODEL:-ensemble-effnet-c5-lr-0.005-tin}", "-n", "1", "-p", "8181", "-s", "192.168.79.12:8180"]
    network_mode: "host"
    depends_on:
      - head-server

  s2-server:
    image: iobt26-server:latest
    container_name: iobt26-s2-server
    volumes:
      - ./system:/app/system
      - ./models:/app/models:ro
      - ./logs:/app/logs
      - ./3rdparty:/app/3rdparty
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    restart: "no"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["python3", "system/single_server.py"]
    command: ["-m", "${FAIL_MODEL:-ensemble-effnet-c5-lr-0.005-tin}", "-n", "2", "-p", "8182", "-s", "192.168.79.12:8180"]
    network_mode: "host"
    depends_on:
      - head-server

  original-server:
    image: iobt26-server:latest
    container_name: iobt26-original-server
    volumes:
      - ./system:/app/system
      - ./models:/app/models:ro
      - ./logs:/app/logs
      - ./3rdparty:/app/3rdparty
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    restart: "no"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["python3", "system/single_server.py"]
    command: ["-m", "${ORIGINAL_MODEL:-effnet-b0}", "--original", "-p", "8190"]
    network_mode: "host"