version: '3.8'

services:
  s1-server:
    build:
      context: .
      dockerfile: Dockerfile.s1
      tags: ["iobt25-s1-server:latest"]
    container_name: iobt25-s1-server
    ports:
      - "8180:8180"
    volumes:
      # Mount your Python source code for development (comment out for production)
      - ./system:/app/system
      # Mount your ONNX models directory
      - ./models:/app/models:ro
      # Mount logs directory (optional)
      - ./logs:/app/logs
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Jetson-specific runtime requirements
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Override default command if needed
    command: ["-m", "ensemble-effnet-c5-lr-0.005-tin", "-n", "1", "-p", "8180", "-s", "localhost:8182"] 