# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"B\n\x0ePredictRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\x12\r\n\x05input\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\"X\n\x0fPredictResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x12\n\nfull_model\x18\x03 \x01(\x08\x12\x12\n\nhas_result\x18\x04 \x01(\x08\x32\x8e\x02\n\x0e\x45ncoderService\x12,\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\x12\x30\n\x0bPredictFull\x12\x0f.PredictRequest\x1a\x10.PredictResponse\x12\x33\n\x0ePredictForward\x12\x0f.PredictRequest\x1a\x10.PredictResponse\x12\x34\n\x0fPredictOriginal\x12\x0f.PredictRequest\x1a\x10.PredictResponse\x12\x31\n\x0cPredictSplit\x12\x0f.PredictRequest\x1a\x10.PredictResponse2;\n\x0bHeadService\x12,\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTREQUEST._serialized_start=19
  _PREDICTREQUEST._serialized_end=85
  _PREDICTRESPONSE._serialized_start=87
  _PREDICTRESPONSE._serialized_end=175
  _ENCODERSERVICE._serialized_start=178
  _ENCODERSERVICE._serialized_end=448
  _HEADSERVICE._serialized_start=450
  _HEADSERVICE._serialized_end=509
# @@protoc_insertion_point(module_scope)
